// Manually authored prost types matching proto/sentryavtt.proto.
// Generated by prost-build in production.

use prost::{Enumeration, Message, Oneof};

// ─── Top-level envelope ────────────────────────────────────────────────

#[derive(Clone, PartialEq, Message)]
pub struct Envelope {
    #[prost(uint64, tag = "1")]
    pub sequence: u64,
    #[prost(uint64, tag = "2")]
    pub timestamp_ms: u64,
    #[prost(enumeration = "MessageType", tag = "3")]
    pub r#type: i32,
    #[prost(
        oneof = "envelope::Payload",
        tags = "10, 11, 12, 13, 14, 15, 16, 20, 21, 22, 23, 24, 25, 26, 30, 31, 32, 40"
    )]
    pub payload: Option<envelope::Payload>,
}

pub mod envelope {
    use super::*;

    #[derive(Clone, PartialEq, Oneof)]
    pub enum Payload {
        // Requests
        #[prost(message, tag = "10")]
        ScanReq(super::ScanRequest),
        #[prost(message, tag = "11")]
        CancelScanReq(super::CancelScanRequest),
        #[prost(message, tag = "12")]
        GetStatusReq(super::GetStatusRequest),
        #[prost(message, tag = "13")]
        PingReq(super::PingRequest),
        #[prost(message, tag = "14")]
        QuarantineListReq(super::QuarantineListRequest),
        #[prost(message, tag = "15")]
        QuarantineRestoreReq(super::QuarantineRestoreRequest),
        #[prost(message, tag = "16")]
        QuarantineDeleteReq(super::QuarantineDeleteRequest),
        // Responses
        #[prost(message, tag = "20")]
        ScanRes(super::ScanResponse),
        #[prost(message, tag = "21")]
        CancelScanRes(super::CancelScanResponse),
        #[prost(message, tag = "22")]
        StatusRes(super::StatusResponse),
        #[prost(message, tag = "23")]
        PongRes(super::PongResponse),
        #[prost(message, tag = "24")]
        QuarantineListRes(super::QuarantineListResponse),
        #[prost(message, tag = "25")]
        QuarantineRestoreRes(super::QuarantineRestoreResponse),
        #[prost(message, tag = "26")]
        QuarantineDeleteRes(super::QuarantineDeleteResponse),
        // Events
        #[prost(message, tag = "30")]
        ThreatDetected(super::ThreatDetected),
        #[prost(message, tag = "31")]
        ScanProgress(super::ScanProgress),
        #[prost(message, tag = "32")]
        CoreStatus(super::CoreStatus),
        // Errors
        #[prost(message, tag = "40")]
        Error(super::ErrorMessage),
    }
}

// ─── Enums ─────────────────────────────────────────────────────────────

#[derive(Clone, Copy, Debug, PartialEq, Eq, Enumeration)]
pub enum MessageType {
    Unspecified = 0,
    Request = 1,
    Response = 2,
    Event = 3,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Enumeration)]
pub enum ScanState {
    Unspecified = 0,
    Queued = 1,
    Running = 2,
    Completed = 3,
    Cancelled = 4,
    Error = 5,
}

// ─── Requests ──────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Message)]
pub struct GetStatusRequest {}

#[derive(Clone, PartialEq, Message)]
pub struct PingRequest {}

#[derive(Clone, PartialEq, Message)]
pub struct ScanRequest {
    #[prost(string, tag = "1")]
    pub target_path: String,
    #[prost(bool, tag = "2")]
    pub recursive: bool,
}

#[derive(Clone, PartialEq, Message)]
pub struct CancelScanRequest {
    #[prost(string, tag = "1")]
    pub scan_id: String,
}

// ─── Responses ─────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Message)]
pub struct StatusResponse {
    #[prost(string, tag = "1")]
    pub version: String,
    #[prost(int32, tag = "2")]
    pub active_scans: i32,
    #[prost(uint64, tag = "3")]
    pub files_scanned: u64,
    #[prost(uint64, tag = "4")]
    pub threats_blocked: u64,
    #[prost(uint64, tag = "5")]
    pub processes_watched: u64,
    #[prost(uint64, tag = "6")]
    pub quarantine_count: u64,
    #[prost(bool, tag = "7")]
    pub service_running: bool,
    #[prost(string, tag = "8")]
    pub signature_age: String,
}

#[derive(Clone, PartialEq, Message)]
pub struct PongResponse {
    #[prost(uint64, tag = "1")]
    pub server_time_ms: u64,
}

#[derive(Clone, PartialEq, Message)]
pub struct ScanResponse {
    #[prost(string, tag = "1")]
    pub scan_id: String,
    #[prost(enumeration = "ScanState", tag = "2")]
    pub state: i32,
    #[prost(uint32, tag = "3")]
    pub files_queued: u32,
}

#[derive(Clone, PartialEq, Message)]
pub struct CancelScanResponse {
    #[prost(string, tag = "1")]
    pub scan_id: String,
    #[prost(bool, tag = "2")]
    pub ok: bool,
    #[prost(string, tag = "3")]
    pub message: String,
}

// ─── Events ────────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Message)]
pub struct ScanProgress {
    #[prost(string, tag = "1")]
    pub scan_id: String,
    #[prost(uint32, tag = "2")]
    pub files_scanned: u32,
    #[prost(uint32, tag = "3")]
    pub files_total: u32,
    #[prost(uint32, tag = "4")]
    pub threats_found: u32,
    #[prost(string, tag = "5")]
    pub current_file: String,
    #[prost(double, tag = "6")]
    pub progress_pct: f64,
}

#[derive(Clone, PartialEq, Message)]
pub struct ThreatDetected {
    #[prost(string, tag = "1")]
    pub path: String,
    #[prost(string, tag = "2")]
    pub hash: String,
    #[prost(string, tag = "3")]
    pub threat_name: String,
    #[prost(enumeration = "threat_detected::Severity", tag = "4")]
    pub severity: i32,
}

pub mod threat_detected {
    use prost::Enumeration;

    #[derive(Clone, Copy, Debug, PartialEq, Eq, Enumeration)]
    pub enum Severity {
        Unspecified = 0,
        Low = 1,
        Medium = 2,
        High = 3,
        Critical = 4,
    }
}

#[derive(Clone, PartialEq, Message)]
pub struct CoreStatus {
    #[prost(enumeration = "core_status::State", tag = "1")]
    pub state: i32,
    #[prost(string, tag = "2")]
    pub detail: String,
}

pub mod core_status {
    use prost::Enumeration;

    #[derive(Clone, Copy, Debug, PartialEq, Eq, Enumeration)]
    pub enum State {
        Unspecified = 0,
        Starting = 1,
        Ready = 2,
        Busy = 3,
        Error = 4,
        ShuttingDown = 5,
    }
}

#[derive(Clone, PartialEq, Message)]
pub struct ErrorMessage {
    #[prost(string, tag = "1")]
    pub code: String,
    #[prost(string, tag = "2")]
    pub message: String,
}

impl std::fmt::Display for ErrorMessage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "[{}] {}", self.code, self.message)
    }
}

// ─── Quarantine ───────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Message)]
pub struct QuarantineListRequest {}

#[derive(Clone, PartialEq, Message)]
pub struct QuarantineEntry {
    #[prost(string, tag = "1")]
    pub id: String,
    #[prost(string, tag = "2")]
    pub original_path: String,
    #[prost(string, tag = "3")]
    pub quarantined_path: String,
    #[prost(string, tag = "4")]
    pub quarantined_at: String,
    #[prost(string, tag = "5")]
    pub hash: String,
    #[prost(string, tag = "6")]
    pub threat_name: String,
    #[prost(int32, tag = "7")]
    pub severity: i32,
    #[prost(string, tag = "8")]
    pub status: String,
}

#[derive(Clone, PartialEq, Message)]
pub struct QuarantineListResponse {
    #[prost(message, repeated, tag = "1")]
    pub entries: Vec<QuarantineEntry>,
}

#[derive(Clone, PartialEq, Message)]
pub struct QuarantineRestoreRequest {
    #[prost(string, tag = "1")]
    pub id: String,
}

#[derive(Clone, PartialEq, Message)]
pub struct QuarantineRestoreResponse {
    #[prost(string, tag = "1")]
    pub id: String,
    #[prost(bool, tag = "2")]
    pub ok: bool,
    #[prost(string, tag = "3")]
    pub message: String,
}

#[derive(Clone, PartialEq, Message)]
pub struct QuarantineDeleteRequest {
    #[prost(string, tag = "1")]
    pub id: String,
}

#[derive(Clone, PartialEq, Message)]
pub struct QuarantineDeleteResponse {
    #[prost(string, tag = "1")]
    pub id: String,
    #[prost(bool, tag = "2")]
    pub ok: bool,
    #[prost(string, tag = "3")]
    pub message: String,
}
